function dz = dyn_turtlebot_example(tdummy,in2,udummy)
%DYN_TURTLEBOT_EXAMPLE
%    DZ = DYN_TURTLEBOT_EXAMPLE(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Apr-2020 14:59:49

a = in2(5,:);
theta = in2(3,:);
v = in2(4,:);
w = in2(6,:);
dz = [v.*cos(theta);v.*sin(theta);w;a;0.0;0.0];
